FROM golang:1.18 as build

WORKDIR /go/src/app
COPY ./k8s_metrics_parser/json_parser/ .

RUN go mod download
RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static-debian11
COPY --from=build /go/bin/app /
CMD ["/app"]
